import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import '../styles/card.css';
import Sidebar from '../components/sidebar/Sidebar';
import Footer from '../components/footer/footer'
import Header from '../components/header/HeaderIndex'
import { AuthProvider } from '@/context/AuthContext';
import GlobalWrapper from '@/components/global-wrapper/GlobalWrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans flex flex-col h-screen`}>
        <AuthProvider>
          <div className="flex min-h-screen">
            <Sidebar />
            <div className="flex flex-col flex-1 overflow-x-hidden">
              <Header />
              <main className="flex-1 overflow-y-auto relative">
                <GlobalWrapper>
                  {children}
                </GlobalWrapper>
              </main>
              <Footer />
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}