import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import '../styles/card.css';
import Sidebar from '../components/sidebar/Sidebar';
import Footer from '../components/footer/footer'
import Header from '../components/header/HeaderIndex'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans flex flex-col h-screen`}>
        <div className="flex min-h-screen">
          <Sidebar />
          <div className="flex flex-col flex-1 overflow-x-hidden">
            <Header /> 
            <main className="flex-1 overflow-y-auto">{children}</main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}