import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar, { SidebarItem, SidebarSubItem } from "../components/SidebarV1";
import { BarChart3, Home, Settings, Users } from "lucide-react";
import SidebarTest from "@/components/SidebarV2";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`flex min-h-screen ${geistSans.variable} ${geistMono.variable}`}>
        <Sidebar>
          <SidebarItem icon={<BarChart3 size={20} />} text="Login" href="/login">
            <SidebarSubItem text="Sales Report" href="/reports/sales" />
            <SidebarSubItem text="Market Basket Analysis Report" href="/reports/market-basket-analysis" />
          </SidebarItem>
        </Sidebar>
        <main className="flex-1 p-6">{children}</main>
      </body>
    </html>
  );
}
